@startuml
'https://plantuml.com/sequence-diagram
Class Salle{
   -nom : string
   -nbPlaces : int
}
Class Séance{
    -dateProjection : DateTime
    -tarifNormal : float
    -tarifReduit : float
}
Class Film{
    -titre: string
    -durée minutes : int
    +estAffiche()
}

Class Utilisateur{
    -username : string
    -password : string
    -roles : string
}

Class Reservation{
    -nbPlaces : int
    -dateReservation : DateTime
    -montant : float
}



Reservation --> "1..1" Utilisateur : Un utilisateur réserve une séance
Reservation --> "1..1" Séance : Une séance est réservée
Séance  --> "1..1" Film : Un film est diffusé
Séance --> "1..1" Salle : Une salle est assignée


@enduml